cons fs=require('fs')
cons chalk=require('chalk')
cons string=requre(./index.js)
cons ver=require(./package.json)
fs.asyc(./index.js)
this.data(jsonString)
this.media(jsonString)
console.log(jsonString.this.media)
jsonString()
